# module creation list
# Workflow:
# 1) Edit this TOML to match your IO tree
# 2) Generate L5X, then import in Studio 5000.
# Dependencies and Limitations:
# - All values are required for each module.
# - ParentModule names must be "Local", or match another module in this file.
# - "Backplane" and "Ethernet" can't be imported at the same time.
# - Parents must be defined before any child that references them.
# - Address maps to the module's single Upstream="true" port.

[config]
controller_name = "SZG_FAT34"
target          = "DLR4000"
output_file     = "Backplane.L5X"
output_dir      = "output"

[templates]
EN2TR     = "input/EN2TR_Module.L5X"
IB-E03B_A = "input/IBXXXX_Module.L5X"
BNI006A   = "input/StaXXXX_IOL_Master_Module.L5X"

[modules]
data = [
	{ name="DLR4000",	type="EN2TR",	ParentModule="Local",	Address="2" },
    { name="DLR7000",	type="EN2TR",	ParentModule="Local",	Address="3" },
	{ name="IB4000",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.100" },
	{ name="IB4010",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.101" },
	{ name="IB4020",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.102" },
	{ name="IB4030",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.103" },
	{ name="IB4040",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.104" },
	{ name="IB4050",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.105" },
	{ name="IB4060",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.106" },
	{ name="IB4070",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.107" },
	{ name="IB4080",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.108" },
	{ name="IB4090",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.109" },
	{ name="IB4100",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.110" },
	{ name="IB4110",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.111" },
	{ name="IB4120",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.112" },
	{ name="IB4130",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.113" },
	{ name="IB4140",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.114" },
	{ name="IB4150",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.115" },
	{ name="IB4160",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.116" },
	{ name="IB4170",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.117" },
	{ name="IB4180",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.118" },
	{ name="IB4190",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.119" },
	{ name="IB4200",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.120" },
	{ name="IB4210",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.121" },
	{ name="IB4220",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.122" },
	{ name="IB4230",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.123" },
	{ name="IB4240",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.124" },
	{ name="IB4250",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.125" },
	{ name="IB4260",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.126" },
	{ name="IB4270",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.127" },
	{ name="IB4280",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.128" },
	{ name="IB4281",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.129" },
	{ name="IB4282",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.130" },
	{ name="IB4290",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.131" },
	{ name="IB4300",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.132" },
	{ name="IB4301",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.133" },
	{ name="IB4302",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.134" },
	{ name="IB4310",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.135" },
	{ name="IB4320",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.136" },
	{ name="IB4321",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.137" },
	{ name="IB4322",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.138" },
	{ name="IB4330",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.139" },
	{ name="IB4340",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.140" },
	{ name="IB4350",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.141" },
	{ name="IB4360",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.142" },
	{ name="IB4370",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.143" },
	{ name="IB4380",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.144" },
	{ name="IB4390",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.145" },
	{ name="IB4400",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.146" },
	{ name="IB4410",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.147" },
	{ name="IB4420",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.148" },
	{ name="IB4440",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.149" },
	{ name="IB4450",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.150" },
	{ name="IB4460",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.151" },
	{ name="IB4470",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.152" },
	{ name="IB4480",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.153" },
	{ name="IB4490",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.154" },
	{ name="IB4500",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.155" },
	{ name="IB4510",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.156" },
	{ name="IB4520",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.157" },
	{ name="IB4530",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.158" },
	{ name="IB4540",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.159" },
	{ name="IB4550",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.160" },
	{ name="IB4560",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.161" },
	{ name="IB4570",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.162" },
	{ name="IB4580",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.163" },
	{ name="IB4590",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.164" },
	{ name="IB4600",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.165" },
	{ name="IB4610",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.166" },
	{ name="IB4620",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.167" },
	{ name="IB4630",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.168" },
	{ name="IB4640",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.169" },
	{ name="IB4650",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.170" },
	{ name="IB4660",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.171" },
	{ name="IB4670",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.172" },
	{ name="IB4680",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.173" },
	{ name="IB4690",	type="IB-E03B_A",	ParentModule="DLR4000",	Address="192.168.1.174" },
	{ name="IB7150",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.100" },
	{ name="IB7151",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.101" },
	{ name="IB7152",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.102" },
	{ name="IB7153",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.103" },
	{ name="IB7154",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.104" },
	{ name="IB7155",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.105" },
	{ name="IB7156",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.106" },
	{ name="IB7157",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.107" },
	{ name="IB7158",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.108" },
	{ name="IB7159",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.109" },
	{ name="IB7160",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.110" },
	{ name="IB7161",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.111" },
	{ name="IB7162",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.112" },
	{ name="IB7163",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.113" },
	{ name="IB7164",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.114" },
	{ name="IB7165",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.115" },
	{ name="IB7166",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.116" },
	{ name="IB7167",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.117" },
	{ name="IB7168",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.118" },
	{ name="IB7169",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.119" },
	{ name="IB7170",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.120" },
	{ name="IB7171",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.121" },
	{ name="IB7172",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.122" },
	{ name="IB7173",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.123" },
	{ name="IB7174",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.124" },
	{ name="IB7175",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.125" },
	{ name="IB7176",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.126" },
	{ name="IB7177",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.127" },
	{ name="IB7178",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.128" },
	{ name="IB7179",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.129" },
	{ name="IB7180",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.130" },
	{ name="IB7181",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.131" },
	{ name="IB7182",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.132" },
	{ name="IB7183",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.133" },
	{ name="IB7184",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.134" },
	{ name="IB7185",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.135" },
	{ name="IB7186",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.136" },
	{ name="IB7187",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.137" },
	{ name="IB7188",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.138" },
	{ name="IB7205",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.139" },
	{ name="IB7210",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.140" },
	{ name="IB7301",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.141" },
	{ name="IB7302",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.142" },
	{ name="IB7303",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.143" },
	{ name="IB7304",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.144" },
	{ name="IB7305",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.145" },
	{ name="IB7306",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.146" },
	{ name="IB7307",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.147" },
	{ name="IB7308",	type="IB-E03B_A",	ParentModule="DLR7000",	Address="192.168.1.148" },
]