# Module list (strict schema)
# Explicit per-station IPs, no gap logic.

[config]
controller_name = "Wolf_HybridMainLine"
output_file     = "Masters.L5X"
output_dir      = "output"

[templates]
parent_template = "input/EN2TR_Module.L5X"
device_templates = { IB-E03B_A = "input/IBXXXX_Module.L5X", BNI006A = "input/StaXXXX_IOL_Master_Module.L5X" }

[root_module]
name            = "DLR_IOL"
icp_slot        = 2
ethernet_ip     = "192.168.1.11"
parent_module   = "Local"
parent_mod_port = 1

[stations]
data = [
    { module_name="IOL_Master10000", device_type="BNI006A", ip="192.168.1.100" },
    { module_name="IOL_Master10500", device_type="BNI006A", ip="192.168.1.101" },
    { module_name="IOL_Master11000", device_type="BNI006A", ip="192.168.1.102" },
    { module_name="IOL_Master11500", device_type="BNI006A", ip="192.168.1.103" },
    { module_name="IOL_Master12000", device_type="BNI006A", ip="192.168.1.104" },
    { module_name="IOL_Master12500", device_type="BNI006A", ip="192.168.1.105" },
    { module_name="IOL_Master13000", device_type="BNI006A", ip="192.168.1.106" },
    { module_name="IOL_Master14000", device_type="BNI006A", ip="192.168.1.107" },
    { module_name="IOL_Master14500", device_type="BNI006A", ip="192.168.1.108" },
]

