# module creation list
# Source: Google Sheet 1KSP39BCc8gFVZjXEksdI1uSqvPceI8Tg-CZ2nLyM3tg (IPAddresses tab)

[config]
controller_name = "Wolf_UpperChassisLine"
target          = "Switch_MCP"
output_file     = "NetworkA1.L5X"
output_dir      = "output/Upper Chassis Line"

[templates]
EN2TR     = "input/Templates/EN2TR_Module.L5X"
IB-E03B_A = "input/Templates/IBXXXX_Module.L5X"
BNI006A   = "input/Templates/IOL_Master_Module.L5X"
GLMaster  = "input/Templates/GLMaster_Module.L5X"
GLTap     = "input/Templates/GLTap_Module.L5X"
ELR       = "input/Templates/ELRGateway_Module.L5X"
PIO       = "input/Templates/PointIO_Rack.L5X"
Switch    = "input/Templates/Stratix_Module.L5X"
DLRTap    = "input/Templates/DLRTap_Module.L5X"

[modules]
data = [
    { name="Switch_MCP",      type="Switch",   ParentModule="Local", Address="10.200.201.10" },
    { name="SIO_MCP",         type="PIO",      ParentModule="Local", Address="10.200.201.20" },
    { name="SIO_Master6500",  type="GLMaster", ParentModule="Local", Address="10.200.201.90" },
    { name="ELR4024",         type="ELR",      ParentModule="Local", Address="10.200.201.21" },
    { name="IOL_Master10000", type="BNI006A",  ParentModule="Local", Address="10.200.201.100" },
    { name="IOL_Master10500", type="BNI006A",  ParentModule="Local", Address="10.200.201.101" },
    { name="IOL_Master11000", type="BNI006A",  ParentModule="Local", Address="10.200.201.102" },
    { name="IOL_Master11500", type="BNI006A",  ParentModule="Local", Address="10.200.201.103" },
    { name="IOL_Master12000", type="BNI006A",  ParentModule="Local", Address="10.200.201.104" },
]
