# module creation list
# Source: Google Sheet 1KSP39BCc8gFVZjXEksdI1uSqvPceI8Tg-CZ2nLyM3tg (IPAddresses tab)

[config]
controller_name = "Wolf_UpperChassisLine"
target          = "Switch_MCP"
output_file     = "NetworkA1.L5X"
output_dir      = "output/Upper Chassis Line"

[templates]
EN2TR     = "input/Templates/EN2TR_Module.L5X"
IB-E03B_A = "input/Templates/IBXXXX_Module.L5X"
BNI006A   = "input/Templates/IOL_Master_Module.L5X"
GLMaster  = "input/Templates/GLMaster_Module.L5X"
GLTap     = "input/Templates/GLTap_Module.L5X"
ELR       = "input/Templates/ELRGateway_Module.L5X"
PIO       = "input/Templates/PointIO_Rack.L5X"
Switch    = "input/Templates/Stratix_Module.L5X"
DLRTap    = "input/Templates/DLRTap_Module.L5X"

[modules]
data = [
    { name="Switch_MCP",      type="Switch",   ParentModule="Local", Address="10.200.201.10" },
    { name="SIO_MCP",         type="PIO",      ParentModule="Local", Address="10.200.201.20" },
    { name="SIO_Master6500",  type="GLMaster", ParentModule="Local", Address="10.200.201.90" },
    { name="ELR4024",         type="ELR",      ParentModule="Local", Address="10.200.201.21" },
    { name="_10000IOL", type="BNI006A",  ParentModule="Local", Address="10.200.201.100" },
    { name="_10500IOL", type="BNI006A",  ParentModule="Local", Address="10.200.201.101" },
    { name="_11000IOL", type="BNI006A",  ParentModule="Local", Address="10.200.201.102" },
    { name="_11500IOL", type="BNI006A",  ParentModule="Local", Address="10.200.201.103" },
    { name="_12000IOL", type="BNI006A",  ParentModule="Local", Address="10.200.201.104" },
    { name="SI_4830",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="3",	Address="0" },
	{ name="SI_4800",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="3",	Address="1" },
	{ name="SI_4780",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="3",	Address="2" },
	{ name="SI_4760",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="3",	Address="3" },
	{ name="SI_4730",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="3",	Address="4" },
	{ name="SI_4860",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="4",	Address="0" },
	{ name="SI_4890",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="4",	Address="1" },
	{ name="SI_4910",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="4",	Address="2" },
	{ name="SI_4930",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="4",	Address="3" },
	{ name="SI_4960",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="4",	Address="4" },
	{ name="SI_4995",	type="GLTap",	ParentModule="SIO_Master6500",	ParentModPortId="4",	Address="5" },
]